[package]
name = "revisa-wasm"
version = "0.1.0"
authors = ["Ted Campbell <dev@tynopex.net>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
memalloc = "*"
serde = "*"
serde_json = "*"
serde_derive = "*"
byteorder = "*"
